### ISSUE TITLE
No worries @Remi-Gau, this was just a draft PR. I am still trying to figure out the exact details so I am happy for non immediate feedback.

### ISSUE THREAD

**Issue by russelljjarvis** [brainhackorg/global2022#60]

**Comment by russelljjarvis** [comment]
I wonder if I can keep editing the hack PR even though it has already been integrated into the website once?

**Comment by Remi-Gau** [comment]
yup if you edit the top message the CI will grab the new content and open a PR that I just have to merge. 

Feel free to edit.
