### ISSUE TITLE
Hacking Brainhack!

### ISSUE THREAD

**Issue by amaiacc** [brainhackorg/global2022#69]
## Project title:
Hacking Brainhack!

## Project leader:
Maximilien Chaumon

## Email:
maximilien.chaumon@gmail.com

## Collaborators:
Yu-Fang Yang @ufangYang; Manuela Ruzzoli @MRuzzoli; Adrien Schramm; Alexandra Corneyllie; Svetlana Pinet 

## Brainhack Global 2022 Event:
BrainHack Donostia

## Topic:
Diversity, inclusivity, equality, knowledge base and website design

## What is the purpose of the project:
We're preparing a global MEG/EEG meeting next year in October with our non-profit conference organisation CuttingEEG. We call it CuttingGardens. It is made of "Gardens" that host their own local event, and connect together and with the global community via live sessions. We would like to create a platform similar to https://brainhack.org/global2022/ on which we could:    offer resources for applying Gardens, similar to what Brainhack has here.    collect Garden candidates via a submission form similar to what Brainhack has here for local events.    Display the catalog of tutorial, lectures, and other local events in a dynamic way, perhaps in a similar way as what Brainhack has here for projectsWe have a team of a handful places across the Americas, Europe, and Asia, willing to be a Garden. We'd like to facilitate more joining and think Brainhack is a great model!

## Where can participants find key resources to work on this project:
Original BHG submission: https://github.com/brainhackorg/global2022/issues/52

## What stage is the project on:
1

## Required programming skills for the project:
Tasks for all levels

## Background knowledge needed  on the topic:
No knowledge needed

## Link to project repository:
https://github.com/CuttingGardens

## Goals for Brainhack Donostia 2022:
We'd like to get a first draft or the website up and running. With key features (submission, visualization, roadmap for documents etc.) set up.    sort out and/or adapt applicable resources from here.    set up a submission form similar to what Brainhack has here for local events    Find a way to dynamically display search results like here for projects perhaps even showing this in a calendar, on a world map...

## What will participants learn:
Okay, it's mostly soft skills:    Community    collaborative documentation    Git/GitHub    Jekll (https://jekyllrb.com/)    Hugo (https://gohugo.io/)

## Number of collaborators:
3

## Credit to collaborators:
You'll be credited on the webpage.

## Type of project:
Documentation

## Programming languages:
Web

## Necessary git skills level for the project:
Basic (commit & push)

## Modality:
documentation/event organisation

**Comment by amaiacc** [comment]
yes, sorry, it had a tiny difference in the title(!) so I did not recognize it as a duplicate.

**Comment by Remi-Gau** [comment]
no worries 
will close this one then
