### ISSUE TITLE
Normalisation and artefact correction toolkit for fibre photometry data

### ISSUE THREAD

**Issue by crnolan** [brainhackorg/global2022#95]
### Title

Normalisation and artefact correction toolkit for fibre photometry data

### Leaders

Chris Nolan (Mattermost: @cnolan | Mastodon: @cnolan@fediscience.org)

### Collaborators

Phil Jean-Richard Dit Bressel
Thomas Burton
J Bertran-Gonzalez
Chelsea Goulton

### Brainhack Global 2022 Event

Brainhack Australasia

### Project Description

Studies using optic fibres to record real-time fluorescent biosensors in-vivo are now commonplace, yet despite a large degree of overlap in the techniques used to filter and normalise this data, there is a surprising lack of open tooling around such analysis. This project is an effort to fill this gap by providing flexible Python-based implementations of common normalisation and artefact correction procedures for fluorescent biosensors, along with some basic analysis tools.

### Link to project repository/sources

TBA

### Goals for Brainhack Global

* Generate a comparison of normalisation methods for GCaMP and dLight data
* Create a semi-automated artefact rejection method if required (for uncorrectable artefacts)
* Create an interactive data viewer that can show raw and corrected / normalised data, and allows overlays of rejected signal periods
* Outline a standardised structure for raw and processed data along with the necessary associated metadata — ideally BIDS-friendly

### Good first issues

1. Install the skeleton package from Github repository (to be added)
2. Test existing basic normalisation method using a variety of fibre photometry data
3. Research and document typical biosensor normalisation methods

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/fibrepy

### Skills

Primarily, some knowledge of fluorescent biosensor normalisation and analysis procedures will be useful. We'll be predominantly working in Python, but there will be tasks for all levels of Python competency.

Bonus useful skills:
* Signal processing (we'll be filtering and fitting timeseries data)
* Python interactive visualisation (bokeh / holoviews / vispy)
* BIDS experience - while we won't be attempting to add an official BIDS extension for fibre photometry in this project, we will try to produce data structures that are broadly in line with the BIDS format

### What will participants learn?

* Data manipulation in Python (numpy / pandas)
* Signal filtering in Python
* Basic GitHub collaboration techniques

### Data to use

BYO fibre & behavioural data - we'll create a repository of useful examples.

### Number of collaborators

more

### Credit to collaborators

Project contributors will be listed on the repository README.

### Image

Leave this text if you don't have an image yet.

### Type

data_management, method_development, pipeline_development, visualization

### Development status

1_basic structure

### Topic

systems_neuroscience

### Tools

BIDS

### Programming language

Python

### Modalities

behavioral, other

### Git skills

0_no_git_skills, 1_commit_push, 2_branches_PRs

### Anything else?

Modalities: fibre_photometry

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by crnolan** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by Remi-Gau** [comment]
Adding a link to the ephys bids extension in case this can help prevent wheel reinventions. 

https://docs.google.com/document/u/0/d/1oG-C8T-dWPqfVzL2W8HO3elWK8NIh2cOCPssRGv23n0/mobilebasic

**Comment by crnolan** [comment]
I've been loosely tracking that project, might be some overlap, but the file formats etc. are all quite different.

**Comment by Remi-Gau** [comment]
yup I would not expect file formats to be the same but some metadata may. :-)
